# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [2]:
# Your code here
import pandas as pd 
data = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv')
print(data.shape)
print(data.info())

(4008, 11)
<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   str
 1   ST                         1071 non-null   str
 2   GENDER                     954 non-null    str
 3   Education                  1071 non-null   str
 4   Customer Lifetime Value    1068 non-null   str
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   str
 8   Policy Type                1071 non-null   str
 9   Vehicle Class              1071 non-null   str
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 344.6 KB
None

In [3]:
data.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

#Al revisar los datos se puede ver como en en la columna "Customer Life Time Value" hay que eliminar los porcentajes por lo que en realidad es para la empresa, un beneficio monetario para la empresa, por lo que la propuesta sería convertirlo a un tipo de dato "Float 64".
En cuanto a Number of Open Complaints, debe ser cambiado a "int64" al tratarse del numero de reclamaciones para el seguro, quienes en str pueden tener sentido para un humano pero al sumarlos, python no los interpreta de la misma manera y da error al no poder sumar texto.

In [4]:
unique_values = data.columns
unique_values.unique()

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

In [5]:
data.nunique()

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

#Identificación del número de valores únicos de cada columna

In [6]:
data[['ST', 'GENDER', 'Education', 'Vehicle Class', 'Policy Type', 'Customer', 'Number of Open Complaints']].nunique()

ST                              8
GENDER                          5
Education                       6
Vehicle Class                   6
Policy Type                     3
Customer                     1071
Number of Open Complaints       6
dtype: int64

#determina cuáles parecen ser categóricas

In [7]:
print(data['Vehicle Class'].unique())
print(data['Policy Type'].unique())
print(data['GENDER'].unique())
print(data['Education'].unique())
print(data['ST'].unique())
print(data['Customer'].unique())
print(data['Number of Open Complaints'].unique())

<StringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car',             nan]
Length: 7, dtype: str
<StringArray>
['Personal Auto', 'Corporate Auto', 'Special Auto', nan]
Length: 4, dtype: str
<StringArray>
[nan, 'F', 'M', 'Femal', 'Male', 'female']
Length: 6, dtype: str
<StringArray>
[              'Master',             'Bachelor', 'High School or Below',
              'College',            'Bachelors',               'Doctor',
                    nan]
Length: 7, dtype: str
<StringArray>
['Washington',    'Arizona',     'Nevada', 'California',     'Oregon',
       'Cali',         'AZ',         'WA',          nan]
Length: 9, dtype: str
<StringArray>
['RB50392', 'QZ44356', 'AI49188', 'WW63253', 'GA49547', 'OC83172', 'XZ87318',
 'CF85061', 'DY87989', 'BQ94931',
 ...
 'IK12620', 'GQ66762', 'YT69858', 'XD85577', 'TM65736', 'VJ51327', 'GS98873',
 'CW49887', 'MY31220',       nan]
Length: 1072, dtype: str
<StringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

#Categorias:
Vehicle Class: Tiene 6 valores unicos y 1 valor ausente.
Policy Type: Tiene 3 valores unicos y 1 valor ausente.
GENDER: Contiene 5 valores unicos y 1 dato ausente. En este punto sería importante revisar que no hayan existido errores, ya que F podría siginficar lo mismo que Feamle o Femal. 
Education: Contiene 6 diferentes niveles educativos y 1 valor ausente. En este habría que revisar si Bachelor y Bachelors sigifican lo mismo y corresponde mas biena un error de digitación. 
ST: Contiene 8 valores diferentes y un valor ausente. En este, los datos de 'Cali', 'AZ', 'WA' podrian siginificar lo mismo que California, Washington y Arizona pero escritos de manera diferente. 
Customer: Hay 1071 valores de identificador distintos en esta columna y 1 valor ausente. 
Number of Open Complaints: Contiene 7 valores unicos. en este punto se tendría que revisar porque en en un numero ttoal de quejas abiertas para un prestador de seguros, el fomrato se enuentra como si fuese una fecha.

In [8]:
print(data['Customer Lifetime Value'].max())
print(data['Customer Lifetime Value'].min())

995170.77%
1006460.83%

In [9]:
print(data['Income'].max())
print(data['Income'].min())

99960.0
0.0

In [10]:
print(data['Monthly Premium Auto'].max())
print(data['Monthly Premium Auto'].min())

35354.0
61.0

In [11]:
print(data['Total Claim Amount'].max())
print(data['Total Claim Amount'].min())

2893.239678
0.382107

# Analisis:
Income: los ingresos van de 0 a 99.960. Es posible que existan clientes con ingresos nulos; no debemos asumir que sea un error sin investigar.



Monthly Premium Auto: los valores van de 61 a 35.354. El máximo parece bastante elevado en comparación con el mínimo, por lo que convendría revisar ese registro.



Total Claim Amount: las reclamaciones van de aproximadamente 0,38 a 2.893,24.



Customer Lifetime Value: los valores aparecen con el símbolo %. Aunque ya obtuviste sus extremos, el formato es extraño para un indicador económico y debemos verificar qué representa antes de

#Calcula estadísticas descriptivas, como la media, la mediana, la moda, la desviación estándar y los cuartiles, para comprender la tendencia central y la distribución de los datos de las columnas numéricas. Expón también tus conclusiones a partir de estas estadísticas.

In [12]:
data.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [13]:
#Calculo Media Income, Mediana Income, Moda Income, Desviacion Estandar Income, Q1, Q2 y Q3
print(data['Income'].mean())
print(data['Income'].median())
print(data['Income'].mode())
print(data['Income'].std())
q1 = data['Income'].quantile(0.25)
q2 = data['Income'].quantile(0.50)
q3 = data['Income'].quantile(0.75)
print(q1, q2, q3)

39295.70121381886
36234.0
0    0.0
Name: Income, dtype: float64
30469.427060401842
14072.0 36234.0 64631.0

El ingreso medio (Income) de los clientes es aproximadamente 39.295,70 unidades monetarias.
La mitad de los valores de ingreso está por debajo o en 36.234, y la otra mitad por encima o en ese valor.
El ingreso que aparece con mayor frecuencia es 0.
La desviación estándar es de 30.469,43, lo que refleja una dispersión considerable de los ingresos.
El primer cuartil (Q1) es 14.072 y el tercer cuartil (Q3) es 64.631, por lo que el 50 % central de los ingresos se encuentra aproximadamente entre esos dos valores.
Conclusión general: Los ingresos presentan una dispersión considerable. La media es superior a la mediana, lo que podría indicar que algunos ingresos elevados aumentan el promedio. Además, el valor cero es el que aparece con mayor frecuencia, por lo que convendría revisar esos registros para comprender qué representan.

In [14]:
#Calculo Media Total Claim Amount, Mediana Total Claim Amount, Moda Total Claim Amount, Desviacion Estandar Total Claim Amount, Q1, Q2 y Q3
print(data['Total Claim Amount'].mean())
print(data['Total Claim Amount'].median())
print(data['Total Claim Amount'].mode())
print(data['Total Claim Amount'].std())
q1 = data['Total Claim Amount'].quantile(0.25)
q2 = data['Total Claim Amount'].quantile(0.50)
q3 = data['Total Claim Amount'].quantile(0.75)
print(q1, q2, q3)

404.98690940896364
354.729129
0    321.6
Name: Total Claim Amount, dtype: float64
293.02725992640416
202.157702 354.729129 532.8

- La reclamación media es de aproximadamente 405 unidades monetarias por registro.
- La mediana es inferior a la media. Esto sugiere que algunas reclamaciones de importe elevado podrían estar aumentando el promedio.
- La desviación estándar es de 293,03, lo que refleja diferencias importantes entre los importes de las reclamaciones.
- El 50 % central de los importes está entre 202,16 y 532,80.
Conclusión basada en datos: La compañía podría estudiar las reclamaciones de importe elevado para entender qué tipos de siniestros generan mayores costes. Esto ayudaría a analizar la distribución de los gastos, aunque todavía no podemos afirmar qué clientes o pólizas son más costosos.

In [15]:
#Calculo Media Monthly Premium Auto, Mediana Monthly Premium Auto, Moda Monthly Premium Auto, Desviacion Estandar Monthly Premium Auto, Q1, Q2 y Q3
print(data['Monthly Premium Auto'].mean())
print(data['Monthly Premium Auto'].median())
print(data['Monthly Premium Auto'].mode())
print(data['Monthly Premium Auto'].std())
q1 = data['Monthly Premium Auto'].quantile(0.25)
q2 = data['Monthly Premium Auto'].quantile(0.50)
q3 = data['Monthly Premium Auto'].quantile(0.75)
print(q1, q2, q3)

193.234360410831
83.0
0    65.0
Name: Monthly Premium Auto, dtype: float64
1601.1903685776203
68.0 83.0 109.5

- Muchas primas mensuales se concentran en valores relativamente bajos, como sugiere el intervalo entre los cuartiles.
- Algunos registros tienen primas mucho más altas y podrían estar elevando la media.
- La desviación estándar de 1.601,19 es extraordinariamente alta en comparación con la mediana de 83.
Conclusión bsada en datos: conviene comprobar si hay primas excepcionalmente elevadas, errores de registro o alguna característica del dataset que explique esa diferencia.

In [ ]:
print(data['Vehicle Class'].describe())
print(data['Policy Type'].describe())
print(data['GENDER'].describe())
print(data['ST'].describe())
print(data['Education'].describe())

1. Vehicle Class: existen 6 categorías diferentes. La más frecuente es Four-Door Car, con 576 registros. Esto indica que los coches de cuatro puertas son la clase de vehículo más representada en los datos analizados.
2. Policy Type: existen 3 categorías diferentes. Personal Auto es la más frecuente, con 780 registros, lo que representa aproximadamente el 72,8 % de los valores no ausentes. Por tanto, predominan las pólizas de tipo personal.
3. GENDER: hay 5 categorías diferentes y F es la más frecuente, con 457 registros. Además, solo hay 954 valores no ausentes, por lo que esta columna contiene datos faltantes. También conviene revisar las categorías para detectar posibles etiquetas inconsistentes.
4. ST: existen 8 categorías diferentes. Oregon es la más frecuente, con 320 registros. Es recomendable comprobar si algunos estados aparecen escritos con abreviaturas o nombres alternativos, ya que esto podría fragmentar las categorías.
5. Education: existen 6 categorías diferentes. Bachelor es la más frecuente, con 324 registros. Conviene verificar si Bachelor y Bachelors representan la misma categoría, para evitar duplicidades en el análisis.

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [16]:
# Your code here
data.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [17]:
frequency = data['ST'].value_counts()
print(frequency)

ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [18]:
frequency.sort_values()

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Arizona       186
California    211
Oregon        320
Name: count, dtype: int64

In [19]:
frequency.sort_values().head()

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [20]:
# Your code here
ptype = data['Policy Type'].value_counts()
print(ptype)

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [21]:
ptype.idxmax()

'Personal Auto'

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [22]:
# Your code here
data.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [23]:
# Your code here
personal_auto = data.loc[data['Policy Type'] == 'Personal Auto']
print(personal_auto)

     Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master
1     QZ44356     Arizona      F              Bachelor
2     AI49188      Nevada      F              Bachelor
4     GA49547  Washington      M  High School or Below
5     OC83172      Oregon      F              Bachelor
...       ...         ...    ...                   ...
1065  XD85577        Cali      M              Bachelor
1066  TM65736      Oregon      M                Master
1067  VJ51327        Cali      F  High School or Below
1068  GS98873     Arizona      F              Bachelor
1070  MY31220  California      F               College

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0
1                 697953.59%      0.0                  94.0
2                1288743.17%  48767.0                 108.0
4                 536307.65%  36357.0                  68.0
5                 825629.78%  62902.0                  69.0
...                      ...      ...                   ...
1065              284226.69%  69417.0                  73.0
1066              305955.03%  38644.0                  78.0
1067             2031499.76%  63209.0                 102.0
1068              323912.47%  16061.0                  88.0
1070              899704.02%  54230.0                 112.0

     Number of Open Complaints    Policy Type  Vehicle Class  \
0                       1/0/00  Personal Auto  Four-Door Car
1                       1/0/00  Personal Auto  Four-Door Car
2                       1/0/00  Personal Auto   Two-Door Car
4                       1/0/00  Personal Auto  Four-Door Car
5                       1/0/00  Personal Auto   Two-Door Car
...                        ...            ...            ...
1065                    1/1/00  Personal Auto  Four-Door Car
1066                    1/1/00  Personal Auto  Four-Door Car
1067                    1/2/00  Personal Auto            SUV
1068                    1/0/00  Personal Auto  Four-Door Car
1070                    1/0/00  Personal Auto   Two-Door Car

      Total Claim Amount
0               2.704934
1            1131.464935
2             566.472247
4              17.269323
5             159.383042
...                  ...
1065           30.874869
1066          361.455219
1067          207.320041
1068          633.600000
1070          537.600000

[780 rows x 11 columns]

In [24]:
corporate_auto = data.loc[data['Policy Type'] == 'Corporate Auto']
print(corporate_auto)

     Customer          ST GENDER             Education  \
3     WW63253  California      M              Bachelor
6     XZ87318      Oregon      F               College
7     CF85061     Arizona      M                Master
8     DY87989      Oregon      M              Bachelor
12    DP39365  California    NaN                Master
...       ...         ...    ...                   ...
1045  WZ31900      Oregon      F              Bachelor
1050  BJ53923     Arizona      M  High School or Below
1052  FB23788      Oregon      M  High School or Below
1056  PI47776      Oregon      F              Bachelor
1059  YG44474      Oregon      M               College

     Customer Lifetime Value   Income  Monthly Premium Auto  \
3                 764586.18%      0.0                 106.0
6                 538089.86%  55350.0                  67.0
7                 721610.03%      0.0                 101.0
8                2412750.40%  14072.0                  71.0
12                879879.70%  77026.0                 110.0
...                      ...      ...                   ...
1045              864970.06%  94389.0                 107.0
1050              260027.21%  51978.0                  66.0
1052              882883.50%  86721.0                 111.0
1056              253070.51%  89451.0                  63.0
1059             1401472.13%  54193.0                 117.0

     Number of Open Complaints     Policy Type  Vehicle Class  \
3                       1/0/00  Corporate Auto            SUV
6                       1/0/00  Corporate Auto  Four-Door Car
7                       1/0/00  Corporate Auto  Four-Door Car
8                       1/0/00  Corporate Auto  Four-Door Car
12                      1/2/00  Corporate Auto  Four-Door Car
...                        ...             ...            ...
1045                    1/0/00  Corporate Auto            SUV
1050                    1/0/00  Corporate Auto  Four-Door Car
1052                    1/0/00  Corporate Auto            SUV
1056                    1/0/00  Corporate Auto  Four-Door Car
1059                    1/0/00  Corporate Auto            SUV

      Total Claim Amount
3             529.881344
6             321.600000
7             363.029680
8             511.200000
12            472.029737
...                  ...
1045           85.063708
1050          144.782152
1052          532.800000
1056           61.769564
1059          720.752945

[234 rows x 11 columns]

In [25]:
print("Personal auto average income is:",personal_auto['Income'].mean())
print("Corporate auto avergae income is: ",corporate_auto['Income'].mean())

Personal auto average income is: 38180.69871794872
Corporate auto avergae income is:  41390.31196581197

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
# Your code here